### ISSUE TITLE
Need a little training

### ISSUE THREAD

**Issue by safeandfree** [open-austin/bodycam#14]
Hey Mateo, I think I kind of know what to do, but I'm afraid I'll mess up your awesome code. If you could find a few minutes, we could do a quick screen share and I'm sure you can tell me what I need to edit text.

**Comment by safeandfree** [comment]
OK, I have downloaded GitHub, pulled the repository to my desktop, made a new branch for my edits so I don't muck things up, picked something to edit, created a little .txt file with the edit, added the edited file back to the repository using command shell, but I can't figure out how to tell the system where the edit should go. I wasn't the person actually using GitHub in my job (as I guess you can tell) although I'm a quick learner. If you don't have time for this, maybe you can point me to someone who can train me? I will pay for their time.

**Comment by mateoclarke** [comment]
https://github.com/open-austin/bodycam/wiki
